# version: 2

# updates:
#   - package-ecosystem: "terraform"
#     directory: "/"
#     schedule:
#       interval: "daily"
#     open-pull-requests-limit: 10
#     reviewers:
#       - "dependabot[bot]"
#       - "dependabot-preview[bot]"
#       - "dependabot[bot]"
#       - "dependabot-preview[bot]"
#     labels:
#       - "dependencies"
#       - "terraform"
#       - "dependabot"
#     ignore:
#       - dependency-name: "terraform"
#         versions:
#           - "0.12.0"
#           - "0.12.1"
#           - "0.12.2"
#           - "0.12.3"
#           - "0.12.4"
#           - "0.12.5"
#           - "0.12.6"
#           - "0.12.7"
#           - "0.12.8"
#           - "0.12.9"
#           - "0.12.10"
#           - "0.12.11"
#           - "0.12.12"
#           - "0.12.13"
#           - "0.12.14"
#           - "0.12.15"
#           - "0.12.16"
#           - "0.12.17"
#           - "0.12.18"
#           - "0.12.19"
#           - "0.12.20"
#           - "0.12.21"
#           - "0.12.22"
#           - "0.12.23"
#           - "0.12.24"
#           - "0.12.25"
#           - "0.12.26"
#           - "0.12.27"
#           - "0.12.28"
#           - "0.12.29"
#           - "0.13.0"
#           - "0.13.1"
#           - "0.13.2"
#           - "0.13.3"
#           - "0.13.4"
#           - "0.13.5"
#           - "0.14.0"
#           - "0.14.1"
#           - "0.14.2"
#           - "0.14.3"
#           - "0.14.4"
#           - "0.14.5"
#           - "0.14.6"
#           - "0.14.7"
#           - "0.14.8"
#           - "0.14.9"
#           - "0.14.10"
#           - "0.14.11"
#           - "0.14.12"
#           - "0.15.0"
#           - "0.15.1"
#           - "0.15.2"
#           - "0.15.3"
#           - "0.15.4"
#           - "0.15.5"


# # YAML data
# # Path: recipe_terraform\.github\workflows\terraform.yml

               

