name: "Code quality"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
superlinter:
  name: Lint code base
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_TERRAFORM: true
          DISABLE_ERRORS: false
          VALIDATE_BASH: true
          VALIDATE_PYTHON: true
          VALIDATE_MD: true
          VALIDATE_YAML: true
