name: "Code quality"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  superlinter:
    name: "Lint code base"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Lint code base"
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Linting rules
          VALIDATE_TERRAFORM: true
          TERRAFORM_VERSION: 0.12.29
          TERRAFORM_VALIDATE_WITH_VERSION: true
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: .markdown-lint.yml
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint.yml
          VALIDATE_JSON: true
          JSON_CONFIG_FILE: .jsonlintrc
          VALIDATE_BASH: true

      - name: "add profile credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: "terraform init"
        run: terraform init
      - name: "terraform validate"
        run: terraform validate
      - name: "terraform issues"
        run: tflint --error-with-issues
      - name: tflint  
        run: tflint --error-with-issues --deep
        
      

        

        
          

 
